name: Generate Arcade Contribution Graph

on:
  schedule:
    # Run automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual run
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Arcade Contribution Graphs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Push SVGs to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: pacman-output
          force_orphan: true
